### PR TITLE
Base initialization of role

### PR DESCRIPTION
**Pull request by jfrappier**
Added standalone playbook to test GoCD install
added GoCD Agent playbook
Fixed host group in gocdagnt.yml
Updated gocdagnt selinux prereq package for python
Created default go-agent config and play to copy to agent
Added var for testing java
Moved items to vars, added handler
Moved gocdagnt items to vars, handlers
Moving stand alone playbook to role
Reformated playbook for GoCD into role (untested)
Tested server install for GoCD role
Created role for GoCD Agent
Updated README.md for Go server and agent roles

### CODE REVIEW

**Comment by Mierdin** [comment]
@jfrappier FYI you may want to set up a proper configuration with your name and email address so Git knows who you are - then make sure it's present in your github settings so you get credit for the commit.

**Comment by jfrappier** [comment]
odd; thanks I'll look into it.

**Comment by jfrappier** [comment]
@Mierdin any ideas why that might happen?  git config --list shows my email and username, and when I check in my github settings it shows my Windows 8.1 box which is where I pushed that from.

**Comment by Mierdin** [comment]
Is that email address listed in your GitHub settings?

**Comment by jfrappier** [comment]
Yes, and marked as primary.

**Comment by Mierdin** [comment]
What's your commit workflow like? Are you using any special tools or extra flags when you commit?

**Comment by Mierdin** [comment]
Also, merry christmas!

**Pull request merged**
